services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: notes_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped

