---
name: Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images using docker-compose
        run: |
          docker-compose -f docker-compose.yml build

      - name: Tag and push app image to Docker Hub
        run: |
          # Tag the built image
          docker tag fib_notes_app ${{ secrets.DOCKERHUB_USERNAME }}/fib_notes:latest
          docker tag fib_notes_app ${{ secrets.DOCKERHUB_USERNAME }}/fib_notes:${GITHUB_REF_NAME}
          # Push both tags
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fib_notes:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fib_notes:${GITHUB_REF_NAME}

      - name: Optional: Output built images
        run: docker images
